stage name: 'build', concurrency: 1

node {
    mvn "clean install -DskipTests"
}

stage name: 'test', concurrency: 3

node {
    mvn "-B test"
}

stage 'approve'
timeout(time: 1, unit: 'DAYS') {
    input message: 'Do you want to deploy?'
}
stage name: 'deploy', concurrency: 1
node {
    mvn "install"
}


def mvn(args) {
    sh "${tool 'm3'}/bin/mvn ${args}"
}

