stage name: 'build', concurrency: 1

node {
    def mvnHome = tool 'm3'
    sh "${mvnHome}/bin/mvn -B clean install -DskipTests"
}



stage name: 'test', concurrency: 3

node {
    def mvnHome = tool 'm3'
    sh "${mvnHome}/bin/mvn -B test"
}

stage 'approve'
timeout(time: 1, unit: 'DAYS') {
    input message: 'Do you want to deploy?'
}
stage name: 'deploy', concurrency: 1
node {
    def mvnHome = tool 'm3'
    sh "${mvnHome}/bin/mvn mvn deploy"
}

